### ISSUE TITLE
Function: $lintall

### ISSUE THREAD

**Issue by mszabolcs-dev** [MarinMakers/eyebot#7]
Making a function to **removeEveryRole** from a person **except** the highest.

```javascriptconst memberRanks = guild.member.roles.filter(role => /* Is role.name in rank array? */)
if (memberRanks.length > 1) {  
  const ranksToRemove = memberRanks  
    .sort((a, b) => b.calculatedPosition - a.calculatedPosition) // Get roles in descending order  
    .slice(1) // Get all entries including and after index 1  
  await guild.member.removeRoles(ranksToRemove)  
}
```

![image](https://user-images.githubusercontent.com/11245344/41493033-c152e868-7103-11e8-878d-f7621e812311.png)

**Comment by milesflo** [comment]
I might have sniped this one from ya... Hehe.
See https://github.com/milesflo/dusty/pull/8

**Comment by mszabolcs-dev** [comment]
This feature was sniped by milesflo. For further information check [#8](https://github.com/milesflo/dusty/pull/8)
